import Head from 'next/head' 
import Carousel from '../components/Carousel'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App with tailwind-element - Carousel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
         <Carousel/> 
      </main>

      <footer className={styles.footer}>
         
      </footer>
    </div>
  )
}
